repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace        # elimina espacios al final de línea
      - id: end-of-file-fixer          # asegura que haya salto de línea final
      - id: check-yaml                 # valida archivos YAML
      - id: check-added-large-files    # evita commits de archivos enormes

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black                       # formatea Python automáticamente

  - repo: https://gitlab.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8                      # chequea estilo y errores PEP8

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.12.0
    hooks:
      - id: isort                       # ordena imports automáticamente
